// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"io"

	"github.com/spcameron/press"
)

func MarkdownHTML(body press.HTML) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) error {
		if body == nil {
			return nil
		}
		return body.Write(w)
	})
}

var _ = templruntime.GeneratedTemplate
