#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/tidy

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

source "$ROOT_DIR/scripts/lib/lib.sh"

tidy() {
  info "Running go mod tidy..."
  go mod tidy -v
  ok "... complete."
}

go_format() {
  info "Running go fmt..."
  go fmt ./...
  ok "... complete."
}

templ_format() {
  info "Running templ fmt..."
  templ fmt "$ROOT_DIR/templates/"
  ok "... complete."
}

main() {
  need_cmd go
  need_cmd templ

  info "Cleaning up project..."
  tidy
  go_format
  templ_format
  ok "... cleanup complete."
}

main "$@"
