#!/usr/bin/env bash
# shellcheck shell=bash
#
# scripts/tidy

set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

source "$ROOT_DIR/scripts/lib/lib.sh"

tidy() {
  info "Running go mod tidy..."
  go mod tidy -v
  ok "... complete."
}

format() {
  info "Running go fmt..."
  go fmt ./...
  ok "... complete."
}

main() {
  need_cmd go

  info "Cleaning up project..."
  tidy
  format
  ok "... cleanup complete."
}

main "$@"
