name: deploy-pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: test -f build/public/index.html
      # TODO: uncomment when deploying with custom domain name
      # - run: test -f build/public/CNAME
      - run: test -f build/public/assets/css/styles.css

      - uses: actions/upload-pages-artifact@v4
        with:
          path: build/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
